"""Generate the launcher icon for the Pape dictionary app.

Adaptive vector icon (API 26+) plus legacy PNGs for every density (API 24/25).
Glyph: Greek capital Pi from P052 Bold (URW Palatino clone), cream on olive green.
"""
import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/opentype/urw-base35/P052-Bold.otf"
GLYPH_CHAR = "Π"
GREEN, CREAM = "#5C6E3F", "#F5F3EE"
res = Path(sys.argv[1])

# --- vector foreground (108x108 dp canvas, content inside the 66 dp safe zone) ---
font = TTFont(FONT)
gs = font.getGlyphSet()
name = font.getBestCmap()[ord(GLYPH_CHAR)]
bp = BoundsPen(gs)
gs[name].draw(bp)
xmin, ymin, xmax, ymax = bp.bounds
scale = 40.0 / max(xmax - xmin, ymax - ymin)
cx, cy = (xmin + xmax) / 2, (ymin + ymax) / 2
# font units are y-up; Android vector paths are y-down
transform = (scale, 0, 0, -scale, 54 - cx * scale, 54 + cy * scale)
sp = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}".rstrip("0").rstrip("."))
gs[name].draw(TransformPen(sp, transform))
path_data = sp.getCommands()


def vector(fill):
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make_icon.py: Greek capital Pi (P052 Bold) -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="{fill}"
        android:pathData="{path_data}" />
</vector>
"""


(res / "drawable").mkdir(exist_ok=True)
(res / "drawable/ic_launcher_foreground.xml").write_text(vector(CREAM))
(res / "drawable/ic_launcher_monochrome.xml").write_text(vector("#FFFFFFFF"))
(res / "values/ic_launcher_background.xml").write_text(
    f"""<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{GREEN}</color>
</resources>
""")
adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""
(res / "mipmap-anydpi-v26").mkdir(exist_ok=True)
for n in ("ic_launcher", "ic_launcher_round"):
    (res / f"mipmap-anydpi-v26/{n}.xml").write_text(adaptive)

# --- legacy PNGs: round olive badge, rendered 8x and downsampled for clean edges ---
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
big = 8 * 192
im = Image.new("RGBA", (big, big), (0, 0, 0, 0))
d = ImageDraw.Draw(im)
m = big * 2 // 48  # legacy icons keep a small margin (46/48 dp)
d.ellipse((m, m, big - m - 1, big - m - 1), fill=GREEN)
# same proportions as the adaptive icon: 40 dp glyph on a 72 dp visible disc
f = ImageFont.truetype(FONT, 10)
x0, y0, x1, y1 = f.getbbox(GLYPH_CHAR)
size = 10 * (big - 2 * m) * 40 / 72 / max(x1 - x0, y1 - y0)
f = ImageFont.truetype(FONT, round(size))
# centre on the real glyph box (anchor "mm" would centre on ascender/descender)
gx0, gy0, gx1, gy1 = d.textbbox((0, 0), GLYPH_CHAR, font=f)
d.text((big / 2 - (gx0 + gx1) / 2, big / 2 - (gy0 + gy1) / 2), GLYPH_CHAR, font=f, fill=CREAM)
for dens, px in DENSITIES.items():
    out = res / f"mipmap-{dens}"
    out.mkdir(exist_ok=True)
    small = im.resize((px, px), Image.LANCZOS)
    small.save(out / "ic_launcher.png", optimize=True)
    small.save(out / "ic_launcher_round.png", optimize=True)
print("ok", path_data[:60], "...")
